name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [javascript, python]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies (Python)
        if: matrix.language == 'python'
        run: |
          cd phase-3/my-python-project
          python -m pip install --upgrade pip
          pip install -r requirements.txt flake8

      - name: Check Installed Python Packages
        if: matrix.language == 'python'
        run: python -m pip list

      - name: Run flake8 (Python)
        if: matrix.language == 'python'
        run: |
          cd phase-3/my-python-project
          flake8 .

  test:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        language: [javascript, python]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (for JavaScript)
        if: matrix.language == 'javascript'
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache Node.js dependencies
        if: matrix.language == 'javascript'
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('phase-3/my-javascript-project/package-lock.json') }}  
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies (JavaScript)
        if: matrix.language == 'javascript'
        run: |
          cd phase-3/my-javascript-project
          npm ci

      - name: Run Jest tests (JavaScript)
        if: matrix.language == 'javascript'
        run: |
          cd phase-3/my-javascript-project
          npm test

      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache Python dependencies
        if: matrix.language == 'python'
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('phase-3/my-python-project/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (Python)
        if: matrix.language == 'python'
        run: |
          cd phase-3/my-python-project
          pip install -r requirements.txt

      - name: Run pytest (Python)
        if: matrix.language == 'python'
        run: |
          cd phase-3/my-python-project
          pytest
